### ISSUE TITLE
Failure parsing /github/workflow/event.json

### ISSUE THREAD

**Issue by giovannibonetti** [cirrus-actions/email#1]
Thanks for sharing this project! I just got access to Github Actions and have tried using it with the new YML syntax:

```yml
name: Notifications
on: [check_suite]
jobs:
  notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Notify user who commited if the tests failed
        uses: docker://cirrusactions/email:latest
        env:
          APP_NAME: "MyAppName"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
```

However I got a parsing error from Github:

![Screenshot 2019-08-13 21 17 01](https://user-images.githubusercontent.com/3451581/62986100-7698f280-be10-11e9-9246-69e26381daf9.png)

Do you have an idea of what might be wrong?

Thanks in advance!
